confirm("this is a passion project. there is no serious meaning and depth behind all of this. i just want to see how far and how well i can do this.")
confirm("let's get started. a note for you: only answer yes/no, any other answers will screw everything over.")
confirm("the year is 2029.")
confirm("there was a double murder right outside of your apartment.")
confirm("the police sirens wake you, and you're confused as to what has happened.")
confirm("your drone begins making your morning coffee, and you step outside to see what went down.")
confirm("there's blood everywhere, and the people standing around are just standing, appalled at what's happened.")
confirm("there's  a woman crying, who might be a mother, or a significant other, its unclear which she is...")
var c1answer1 = prompt("do you approach?")
    if (c1answer1 === "no") {
        confirm("you stay where you're standing. you don't wish to invade her boundaries.")

    }
    else{
        confirm("you approach her slowly.")
        confirm("she sees you out of the corner of her eye")
        confirm("she asks, are you that guy that lives in 517?")
        confirm("you nod, and ask what's happening")
        confirm("this is the man's mother, and you learn that this was a murder and a suicide.")
        confirm("there was an altercation in which a knife was pulled on the initial victim, and then the murderer killed himself.")

    }
confirm("there's something amiss, you don't quite understand it.")
confirm("at any rate though, you're late for work.")
confirm("upon realization of this fault, you sprint back to 517, to grab your things, and you leave the coffee.")
confirm("you jump on your e-bike and get going.")
confirm("you get a call from a blocked number.")
confirm("if you answer, there's a chance the organization is trailing you.")
var c1answer2 = prompt("answer the call?")
    if (c1answer2 === "yes"){
       confirm("you answer and listen to three seconds of mysterious static through your helmet. shit. someone's onto you for sure.")
       confirm("bad cell signal doesn't happen in this year, plus you're in the middle of the metro area. so there's no way that something so mysterious just happened")
       confirm("you feel uneasy.")
    }
    else{
        confirm("you just let it ring.")
    }
confirm("you arrive at work, almost thirty minutes late.")
confirm("as you walk in, you're flooded with insults from jameson/your boss.")
confirm("you explain that getting out of the apartment was difficult since the police were there.")
confirm("he lets you go. you walk to your desk, dreading the tasklist for the day.")
confirm("you power on your workstation, only to be greeted with ssd failure. great.")
confirm("you take it to IT, and they give you a laptop to use for today.")
confirm("time goes by fast.")
confirm("as you're leaving, the IT guy grabs your attention.")
confirm("as you're pulled into the jungle of wires and pc parts, you notice that your workstation is working, just fine.")
confirm("there's something up here.")
confirm("he turns to you and says that there were weird things in the C:\ drive that may have prevented you from using it this morning.")
confirm("you log in, and are greeted with this strange message, that is password protected.")
var c1answer3 = prompt("will you open it?")
    if (c1answer3 === "yes"){
            confirm("with unease, you double click. it asks for a password.")
            confirm("you have no idea what the password could possibly be.")
            confirm("you just decide to take the files with you for the night.")
    }
        else{
            confirm("intrigued, you load these files onto your flash, and stick it in your backpack. you delete them from the workstation and put it back at your desk.")
        }
confirm("you arrive home.")
confirm("the drone greets you, and hands you a beer. you gladly accept.")
confirm("since it's only activated when YOU walk into the room, its battery is still on high, and its continuing its morning routine, telling you the weather and the news.")
confirm("you shut it off, since you're trying to figure out this password.")
confirm("you think.")
confirm("and think.")
confirm("and thinkkkkkk......................")
confirm("you're at a loss for ideas.")
confirm("you decide to just try and decrypt the files.")
confirm("as it begins, you get up and walk over to the kitchen.")
confirm("that's weird. the coffee mug is...empty?")
confirm("you don't remember drinking it, given the events outside this morning.")
confirm("fear takes over. you run back to your computer, and you realize that the screen has gone completely black.")
confirm("this is what happened to mom and dad. before the org took them, their computers had gone black.")
confirm("shit. shit shit shit! you realize who the blocked number was, where your coffee went, why your ssd failed at work this morning, and now why these files are locked.")
confirm("your heart rate is beginning to reach an unstable rate. your watch begins pinging, telling you to relax, but that won't happen soon.")
confirm("147 and climbing.")
confirm("the panic gets worse, and worse, and even worse. it gets so bad that your breathing is irregular.")
confirm("you fall out of your chair and you start sweating uncontrollably.")
confirm("you hear talking outside of your door.")
confirm("you turn on your drone, to lock the door, since you forgot.")
confirm("the drone never activates.")
confirm("there are white lights appearing under the door, you start to freak out.")
confirm("your watch is violently pinging you, you're at 320 bpm.")
confirm("you pass out.")
confirm("end chapter 1.")
